version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deliverydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  delivery-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DBNAME: deliverydb
      USER_SERVICE_URL: http://mock-user-service:8081 # Points to the mock service
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mock-user-service

  # Mock user service to simulate responses
  mock-user-service:
    image: node:20-alpine
    working_dir: /mock
    volumes:
      - ./mock-user-service:/mock
    command: ["node", "index.js"]
    ports:
      - "8081:8081"

volumes:
  pgdata: